### ISSUE TITLE
How to display a sprite immediatly on the left (or the right)

### ISSUE THREAD

**Issue by Jibus-** [elfketchup/EKVN#11]
I have a set of sprite with different mood (happy, sade, angry etc...).

I couldn't a find a command wich allows to replace instantly a sprite which is positionned on the left (or on the right).

**Comment by elfketchup** [comment]
Well, assuming you've got a sprite named "happy.png" positioned on the left, and you want to replace it with a sprite named "sad.png" then here's how you instantly replace it:

.REMOVESPRITE:happy.png:YES

.ADDSPRITE:sad.png:YES

.ALIGNSPRITE:sad.png:LEFT:0

The "YES" at the end of the "addsprite" and "removesprite" commands makes them appear/disappear instantly. The zero (0) at the end of the "alignsprite" command makes it move into position instantly. 

Most commands like this have gradual transitions (as you've probably found), but they usually have optional parameters to make them take effect at once. :)

**Comment by Jibus-** [comment]
This is just perfect. Thanks you !
