### ISSUE TITLE
Feature request : mirror for sprite

### ISSUE THREAD

**Issue by Jibus-** [elfketchup/EKVN#16]
Sometimes we want to display the sprite on a side but the orientation is not good. The quick way would be to make the mirror image through an imaging software and then add it to the project and call it by .ADDSPRITE. But I wonder if cocos2d cannot manage this.

Would be greate if we can have a new argument for .ADDSPRITE command like .ADDSPRITE:john.png:NO:YES (the last argument would be the mirror image)

As always, thanks for your great work !

**Comment by elfketchup** [comment]
I added a .FLIPSPRITE command, this flips/inverts the sprite; I assume this is what you meant by a mirrored image. The syntax is:

.FLIPSPRITE:(image name)

You can call it right after .ADDSPRITE to instantly make that mirrored image. (It's also more readable than having two boolean parameters in .ADDSPRITE, as that would probably make it harder to edit the script afterwards, having to remember which YES/NO parameter does what).

**Comment by Jibus-** [comment]
Excellent ! Thanks you !

Indeed, it's better to have a separate command.
