### ISSUE TITLE
Feature : ability to zoom on the background or the sprite

### ISSUE THREAD

**Issue by Jibus-** [elfketchup/EKVN#18]
Hello again :)

I was wondering if it is possible to have a function which allows to zoom in gracefully on the background and / or the sprite.

Thanks you

**Comment by elfketchup** [comment]
There's now:

.SCALEBACKGROUND:(scale):(duration)

(example: .SCALEBACKGROUND:2.0:1)

and 

.SCALESPRITE:(sprite name):(scale):(duration)

(example: SCALESPRITE:girl.png:1.5:1.0)

Regarding scale, the "normal" size is 1.0. Setting it to 2.0 will double both the width and height of the image to make it look bigger, and setting it to 0.5 will shrink both by half.

Duration is measured in seconds. If you don't include a duration, it will assume zero by default and changes will take place instantly. (I recommend a duration of 1.0, but it's really up to you and what you think looks best for your game)

**Comment by Jibus-** [comment]
Excellent thanks you as always !
