### ISSUE TITLE
Feature request - support button

### ISSUE THREAD

**Issue by Jibus-** [elfketchup/EKVN#22]
Apple is requiring a support button. It would be nice to have a new button which open a link set in the main menu plist file.

Thanks you :)

**Comment by elfketchup** [comment]
Try it now.

**Comment by Jibus-** [comment]
Text appears and color but the background image file doesn't seem to be taken into account

**Comment by elfketchup** [comment]
OK, try it again; it should look fine now.

**Comment by Jibus-** [comment]
It's perfect. Thanks you for your quick response and work as always :)
