### ISSUE TITLE
Feature request - Auto text display

### ISSUE THREAD

**Issue by Ahrasyl** [elfketchup/EKVN#8]
Would that be possible to add a text feature wich allows to display text automatically (like a cinematic phase) ? The user won't have to tap in, to get the next text.

**Comment by elfketchup** [comment]
There's now a .SETCINEMATICTEXT command to do that, just add it in the parts of the script where you want it to happen (you can disable it by entering .SETCINEMATICTEXT:0 in the script)

**Comment by Ahrasyl** [comment]
Thanks you very much :)
