### ISSUE TITLE
Cocos2D 3.4 out 

### ISSUE THREAD

**Issue by Jibus-** [elfketchup/EKVN#9]
Cocos2D 3.4 is now available, but i can't see if there is now a good support for iPhone 6 & 6+ device. If so, what size and namefile shoud we use ?

This is not an issue but more a support request :)

**Comment by elfketchup** [comment]
As far as I can tell, there is still no "real" support for sprites using iPhone 6 / 6 Plus resolutions in v3.4; the exact same sprites / sprite filenames used by the Retina-Display iPhone 5 are also used by the Retina-HD iPhone 6 / 6 Plus.

It seems that full support for the new iPhone will be delayed until cocos2d v4.0, but no-one really knows when that will happen... one estimate I heard suggested it would be released around summer or fall of this year.

**Comment by Jibus-** [comment]
ok, thanks you !
